name: Node.js CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Set this to the node version you are using
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test # Add this if you have tests
    - name: Start server
      run: npm start &
    - name: Deploy
      run: echo "Add deployment scripts here" # Replace with actual deployment steps
